from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
app = FastAPI(title="StudySync Unified Live")
class UserRegisterSchema(BaseModel):
    name: str
    email: str
    password: str
    major: str = "Computer Science"
class UserLoginSchema(BaseModel):
    email: str
    password: str
@app.post("/api/auth/register")
async def register(p: UserRegisterSchema): return {"status": "success"}
@app.post("/api/auth/login")
async def login(p: UserLoginSchema):
    return {"access_token": "mock", "token_type": "bearer", "username": p.email.split("@")[0].capitalize()}
@app.get("/", response_class=HTMLResponse)
async def serve_login(): return """<!DOCTYPE html><html><head><title>StudySync</title><style>body{background:#0d1117;color:#fff;font-family:sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh;margin:0;}.box{background:#161b22;border:1px solid #30363d;padding:40px;border-radius:8px;text-align:center;}input{width:100%;padding:10px;margin:10px 0;background:#0d1117;border:1px solid #30363d;color:#fff;border-radius:4px;box-sizing:border-box;}button{width:100%;padding:12px;background:#4f46e5;border:none;color:#fff;font-weight:bold;border-radius:4px;cursor:pointer;}</style></head><body><div class="box"><h2>Welcome to StudySync</h2><form id="f"><input type="email" id="e" placeholder="Email" required><input type="password" id="p" placeholder="Password" required><button type="submit">Sign In</button></form><p><a href="/register" style="color:#58a6ff;text-decoration:none;">Create an account</a></p></div><script>document.getElementById("f").addEventListener("submit",async(e)=>{e.preventDefault();const res=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:document.getElementById("e").value,password:document.getElementById("p").value})});if(res.ok){const d=await res.json();localStorage.setItem("username",d.username);window.location.href="/dashboard";}else{alert("Failed");}});</script></body></html>"""
@app.get("/register", response_class=HTMLResponse)
async def serve_register(): return """<!DOCTYPE html><html><head><title>Register</title><style>body{background:#0d1117;color:#fff;font-family:sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh;margin:0;}.box{background:#161b22;border:1px solid #30363d;padding:40px;border-radius:8px;text-align:center;}input{width:100%;padding:10px;margin:10px 0;background:#0d1117;border:1px solid #30363d;color:#fff;border-radius:4px;box-sizing:border-box;}button{width:100%;padding:12px;background:#4f46e5;border:none;color:#fff;font-weight:bold;border-radius:4px;cursor:pointer;}</style></head><body><div class="box"><h2>Join Platform</h2><form id="f"><input type="text" id="n" placeholder="Name" required><input type="email" id="e" placeholder="Email" required><input type="password" id="p" placeholder="Password" required><button type="submit">Register</button></form><p><a href="/" style="color:#58a6ff;text-decoration:none;">Sign In instead</a></p></div><script>document.getElementById("f").addEventListener("submit",async(e)=>{e.preventDefault();const res=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:document.getElementById("n").value,email:document.getElementById("e").value,password:document.getElementById("p").value})});if(res.ok){alert("Success!");window.location.href="/";}});</script></body></html>"""
@app.get("/dashboard", response_class=HTMLResponse)
async def serve_dashboard(): return """<!DOCTYPE html><html><head><title>Workspace</title><style>body{background:#12161a;color:#f0f2f5;font-family:sans-serif;display:flex;margin:0;}.sidebar{width:240px;background:#1a1f26;height:100vh;padding:30px 20px;box-sizing:border-box;position:fixed;}.content{margin-left:240px;padding:40px;width:100%;}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:30px;}.card{background:linear-gradient(135deg,#1e1b4b,#312e81);padding:20px;border-radius:8px;border:1px solid rgba(255,255,255,0.05);}.btn{background:none;border:1px solid #f43f5e;color:#f43f5e;padding:10px;border-radius:4px;cursor:pointer;width:100%;font-weight:bold;}</style></head><body><div class="sidebar"><h2>🎓 StudySync</h2><button class="btn" id="lo">Disconnect</button></div><div class="content"><h1 id="wel">Welcome Back!</h1><p>Collaborative workspace online.</p><div class="grid"><div class="card"><h3>Active Sessions</h3><h2>5</h2></div><div class="card" style="background:linear-gradient(135deg,#2b2212,#453315);"><h3>Peer Rating</h3><h2>4.9 ★</h2></div><div class="card" style="background:linear-gradient(135deg,#231c18,#3a2a22);"><h3>Study Hours</h3><h2>12.4h</h2></div></div></div><script>document.getElementById("wel").innerText=`Welcome, ${localStorage.getItem("username")||"Scholar"}!`;document.getElementById("lo").addEventListener("click",()=>{localStorage.clear();window.location.href="/";});</script></body></html>"""
